"""Thin adapters between UAEA execution contracts and external Harness hosts."""

from .codex_dynamic_tools import (
    DynamicToolBinding,
    HarnessDynamicToolAdapter,
    HarnessToolDispatch,
)
from .event_normalizer import (
    AGENT_OUTPUT,
    CANCELLED,
    COMMAND_EXECUTION,
    CONTEXT_COMPACTION,
    ERROR,
    OBSERVATION,
    PRE_TURN_CONTEXT,
    RAW_EVENT,
    TOKEN_USAGE,
    TOOL_CALL,
    TOOL_RESULT,
    TURN_COMPLETED,
    TURN_STARTED,
    USER_INPUT,
    HarnessEventNormalizer,
    TrajectoryEvent,
)
from .trajectory_writer import (
    HarnessTrajectoryWriter,
    TrajectoryWriteResult,
    TrajectoryWriterStats,
)
from .trajectory_reader import (
    TrajectoryReadError,
    TrajectoryReadResult,
    TrajectoryRecord,
    TrajectoryValidationResult,
    TurnTimeline,
    read_trajectory_jsonl,
    validate_trajectory_records,
)

__all__ = [
    "AGENT_OUTPUT",
    "CANCELLED",
    "COMMAND_EXECUTION",
    "CONTEXT_COMPACTION",
    "DynamicToolBinding",
    "ERROR",
    "HarnessDynamicToolAdapter",
    "HarnessEventNormalizer",
    "HarnessTrajectoryWriter",
    "HarnessToolDispatch",
    "OBSERVATION",
    "PRE_TURN_CONTEXT",
    "RAW_EVENT",
    "TOKEN_USAGE",
    "TOOL_CALL",
    "TOOL_RESULT",
    "TURN_COMPLETED",
    "TURN_STARTED",
    "TrajectoryEvent",
    "TrajectoryReadError",
    "TrajectoryReadResult",
    "TrajectoryRecord",
    "TrajectoryValidationResult",
    "TrajectoryWriteResult",
    "TrajectoryWriterStats",
    "TurnTimeline",
    "USER_INPUT",
    "read_trajectory_jsonl",
    "validate_trajectory_records",
]
